fastlane_version "2.148.0"

default_platform :mac

platform :mac do
  lane :build do 
    build_app(scheme: 'awsosx', 
    export_method: 'development', 
    export_xcargs: '-allowProvisioningUpdates')
  end
end
